substitutions:
  _NEXT_PUBLIC_API_URL: ""
  _NEXT_PUBLIC_SITE_URL: ""

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.web
      - --build-arg
      - NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}
      - --build-arg
      - NEXT_PUBLIC_SITE_URL=${_NEXT_PUBLIC_SITE_URL}
      - -t
      - asia-south1-docker.pkg.dev/ooro-509014/ooro/ooro-web:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-south1-docker.pkg.dev/ooro-509014/ooro/ooro-web:latest

images:
  - asia-south1-docker.pkg.dev/ooro-509014/ooro/ooro-web:latest
