package com.ooro.driver

import android.content.Intent
import android.os.Bundle
import android.provider.Settings
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.viewModels
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.ooro.driver.domain.*

private val OoroYellow = Color(0xFFDFFF00)
private val OoroBackground = Color(0xFFF7F7F4)

class MainActivity : ComponentActivity() {
    private val vm: DriverAppViewModel by viewModels { DriverAppViewModel.factory(applicationContext) }
    override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); setContent { OoroTheme { DriverRoot(vm) } } }
}

@Composable private fun OoroTheme(content: @Composable () -> Unit) { MaterialTheme(colorScheme = lightColorScheme(primary = Color.Black, secondary = OoroYellow, background = OoroBackground, surface = Color.White), content = content) }
@Composable private fun DriverRoot(vm: DriverAppViewModel) { val mode by vm.mode.collectAsState(); when (mode) { AppMode.LOGIN, AppMode.OTP -> AuthScreen(vm, mode); AppMode.FLEET_INQUIRY -> FleetInquiry(vm); AppMode.ONBOARDING -> OnboardingScreen(vm); AppMode.DASHBOARD -> DashboardScreen(vm) } }

@Composable private fun AuthScreen(vm: DriverAppViewModel, mode: AppMode) { var phone by remember { mutableStateOf("") }; var otp by remember { mutableStateOf("") }; val message by vm.message.collectAsState(); Box(Modifier.fillMaxSize().background(OoroBackground), contentAlignment = Alignment.Center) { Column(Modifier.widthIn(max = 440.dp).padding(24.dp)) { Text("OORO", fontSize = 38.sp, fontWeight = FontWeight.Bold); Text("Driver", color = Color.DarkGray); Spacer(Modifier.height(35.dp)); Text(if (mode == AppMode.OTP) "Verify your phone" else "Drive with OORO", fontSize = 28.sp, fontWeight = FontWeight.SemiBold); Text(if (mode == AppMode.OTP) "Enter the six-digit code. Debug mode uses 000000." else "Verified passenger rides. Clearer earnings.", Modifier.padding(top = 8.dp), color = Color.Gray); Spacer(Modifier.height(24.dp)); if (mode == AppMode.LOGIN) { OutlinedTextField(phone, { phone = it }, label = { Text("Phone number") }, singleLine = true, modifier = Modifier.fillMaxWidth()); Button({ vm.requestOtp(phone) }, Modifier.fillMaxWidth().padding(top = 16.dp)) { Text("Continue") } } else { OutlinedTextField(otp, { otp = it.take(6) }, label = { Text("OTP") }, singleLine = true, modifier = Modifier.fillMaxWidth()); Button({ vm.verifyOtp(otp) }, Modifier.fillMaxWidth().padding(top = 16.dp)) { Text("Verify") } }; if (message != null) Text(message!!, Modifier.padding(top = 16.dp), color = Color.Red) } } }

@Composable private fun FleetInquiry(vm: DriverAppViewModel) { Box(Modifier.fillMaxSize().background(OoroBackground), contentAlignment = Alignment.Center) { Column(Modifier.padding(28.dp).widthIn(max = 480.dp)) { Text("OORO Fleet", fontSize = 32.sp, fontWeight = FontWeight.SemiBold); Text("Managing multiple vehicles?", Modifier.padding(top = 10.dp), color = Color.Gray); Spacer(Modifier.height(20.dp)); Text("Fleet tools include bulk vehicle onboarding, driver management, display deployment, analytics and centralized payouts.", lineHeight = 24.sp); Spacer(Modifier.height(24.dp)); Button({ }, Modifier.fillMaxWidth()) { Text("Request callback") }; OutlinedButton({ }, Modifier.fillMaxWidth().padding(top = 10.dp)) { Text("Email OORO Fleet Team") }; TextButton({ vm.logout() }, Modifier.align(Alignment.CenterHorizontally)) { Text("Use an individual driver account") } } } }

@Composable private fun OnboardingScreen(vm: DriverAppViewModel) { val step by vm.step.collectAsState(); val message by vm.message.collectAsState(); when (step) { OnboardingStep.DRIVER_TYPE -> ChoiceStep("How do you work?", "Choose the account type that matches your operation.", listOf("Individual Driver" to { vm.chooseDriverType(DriverType.INDIVIDUAL) }, "Fleet Owner / Fleet Manager" to { vm.chooseDriverType(DriverType.FLEET_OWNER) }), vm); OnboardingStep.PROFILE -> FormStep("Driver profile", "Add the basics needed to operate with OORO.", "Save profile") { vm.advance(OnboardingStep.KYC) }; OnboardingStep.KYC -> FormStep("KYC verification", "Identity, licence, RC and insurance are required before payouts.", "Start verification") { vm.advance(OnboardingStep.VEHICLE) }; OnboardingStep.VEHICLE -> FormStep("Your vehicle", "Register an Auto or Cab and upload its documents.", "Save vehicle") { vm.advance(OnboardingStep.DISPLAY_OWNERSHIP) }; OnboardingStep.DISPLAY_OWNERSHIP -> ChoiceStep("Which display are you using?", "Payout terms may depend on display ownership.", listOf("My Own OORO Display" to { vm.advance(OnboardingStep.PAIR_DISPLAY) }, "Shared / Rented Display" to { vm.advance(OnboardingStep.PAIR_DISPLAY) }, "Company-Owned Display" to { vm.advance(OnboardingStep.PAIR_DISPLAY) }), vm); OnboardingStep.PAIR_DISPLAY -> PairDisplayStep(vm); OnboardingStep.PERMISSIONS -> PermissionStep(vm); OnboardingStep.PAYMENT -> FormStep("Payment setup", "Add UPI or bank details before requesting payouts.", "Save payment details") { vm.advance(OnboardingStep.TERMS) }; OnboardingStep.TERMS -> FormStep("Agreements and consent", "Review driver, location, notification and payout terms.", "Accept and finish") { vm.completeOnboarding() }; OnboardingStep.COMPLETE -> vm.completeOnboarding() } ; if (message != null) Text(message!!, Modifier.padding(16.dp), color = Color.Red) }
@Composable private fun ChoiceStep(title: String, subtitle: String, choices: List<Pair<String, () -> Unit>>, vm: DriverAppViewModel) { Box(Modifier.fillMaxSize().background(OoroBackground), contentAlignment = Alignment.Center) { Column(Modifier.padding(24.dp).widthIn(max = 500.dp)) { Text("OORO Driver", color = Color.Gray); Text(title, Modifier.padding(top = 12.dp), fontSize = 28.sp, fontWeight = FontWeight.SemiBold); Text(subtitle, Modifier.padding(top = 8.dp), color = Color.Gray); Spacer(Modifier.height(24.dp)); choices.forEach { (label, action) -> Button(action, Modifier.fillMaxWidth().padding(vertical = 5.dp)) { Text(label) } }; TextButton({ vm.logout() }, Modifier.align(Alignment.CenterHorizontally)) { Text("Log out") } } } }
@Composable private fun FormStep(title: String, subtitle: String, action: String, onAction: () -> Unit) { var value by remember { mutableStateOf("") }; Box(Modifier.fillMaxSize().background(OoroBackground), contentAlignment = Alignment.Center) { Column(Modifier.padding(24.dp).widthIn(max = 500.dp)) { Text(title, fontSize = 28.sp, fontWeight = FontWeight.SemiBold); Text(subtitle, Modifier.padding(top = 8.dp), color = Color.Gray); Spacer(Modifier.height(22.dp)); OutlinedTextField(value, { value = it }, label = { Text("Details") }, modifier = Modifier.fillMaxWidth(), minLines = 3); Button(onAction, Modifier.fillMaxWidth().padding(top = 16.dp)) { Text(action) } } } }
@Composable private fun PairDisplayStep(vm: DriverAppViewModel) { var code by remember { mutableStateOf("") }; Box(Modifier.fillMaxSize().background(OoroBackground), contentAlignment = Alignment.Center) { Column(Modifier.padding(24.dp).widthIn(max = 500.dp)) { Text("Pair your OORO display", fontSize = 28.sp, fontWeight = FontWeight.SemiBold); Text("Enter the temporary code shown on the Screen Player.", Modifier.padding(top = 8.dp), color = Color.Gray); Spacer(Modifier.height(22.dp)); OutlinedTextField(code, { code = it }, label = { Text("Display pairing code") }, modifier = Modifier.fillMaxWidth()); Button({ vm.pairDisplay(code) }, Modifier.fillMaxWidth().padding(top = 16.dp)) { Text("Connect display") }; Text("Debug mode: use 742981 or OORO-DEMO", Modifier.padding(top = 14.dp), color = Color.Gray, fontSize = 12.sp) } } }
@Composable private fun PermissionStep(vm: DriverAppViewModel) { val context = LocalContext.current; Box(Modifier.fillMaxSize().background(OoroBackground), contentAlignment = Alignment.Center) { Column(Modifier.padding(24.dp).widthIn(max = 500.dp)) { Text("Connect mobility apps", fontSize = 28.sp, fontWeight = FontWeight.SemiBold); Text("OORO uses normalized ride notifications only from providers you explicitly enable. It cannot accept rides, cancel rides or send messages.", Modifier.padding(top = 8.dp), color = Color.Gray, lineHeight = 22.sp); Button({ context.startActivity(Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS)) }, Modifier.fillMaxWidth().padding(top = 22.dp)) { Text("Enable notification access") }; OutlinedButton({ vm.advance(OnboardingStep.PAYMENT) }, Modifier.fillMaxWidth().padding(top = 10.dp)) { Text("Continue to payment setup") } } } }

@Composable private fun DashboardScreen(vm: DriverAppViewModel) { val dashboard by vm.dashboard.collectAsState(); var tab by remember { mutableStateOf("HOME") }; Scaffold(bottomBar = { NavigationBar { listOf("HOME", "RIDES", "EARNINGS", "HELP", "PROFILE").forEach { item -> NavigationBarItem(selected = tab == item, onClick = { tab = item }, icon = { Text(item.take(1)) }, label = { Text(item) }) } } }) { padding -> when (tab) { "HOME" -> HomeContent(vm, dashboard, Modifier.padding(padding)); "RIDES" -> RidesContent(dashboard, Modifier.padding(padding)); "EARNINGS" -> EarningsContent(Modifier.padding(padding)); "HELP" -> HelpContent(Modifier.padding(padding)); else -> ProfileContent(vm, Modifier.padding(padding)) } } }
@Composable private fun HomeContent(vm: DriverAppViewModel, dashboard: DashboardState, modifier: Modifier) { LazyColumn(modifier.fillMaxSize().background(OoroBackground).padding(20.dp), verticalArrangement = Arrangement.spacedBy(14.dp)) { item { Text("Good morning, Driver", fontSize = 27.sp, fontWeight = FontWeight.SemiBold); Text("Ready for verified passenger rides", color = Color.Gray) }; item { Card { Column(Modifier.padding(18.dp)) { Text("TODAY", fontSize = 11.sp, color = Color.Gray); Text("₹${dashboard.todayMinor / 100}", Modifier.padding(top = 8.dp), fontSize = 34.sp, fontWeight = FontWeight.Bold); Text("${dashboard.verifiedRides} verified rides · ${dashboard.advertisingSeconds / 60} min advertising", color = Color.Gray) } } }; item { Card { Column(Modifier.padding(18.dp)) { Text("DISPLAY", fontSize = 11.sp, color = Color.Gray); Text(dashboard.display?.name ?: "Not paired", Modifier.padding(top = 8.dp), fontWeight = FontWeight.SemiBold); Text(dashboard.display?.state?.name?.replace("_", " ") ?: "DISPLAY REQUIRED", color = Color.Gray); Button({ }, Modifier.padding(top = 12.dp)) { Text("My Display") } } } }; if (BuildConfig.ALLOW_DEBUG_SIMULATION) { item { Text("DEBUG RIDE SIMULATION", fontSize = 11.sp, color = Color.Gray); Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { Button({ vm.simulate(RideEventType.RIDE_ACCEPTED) }) { Text("Accepted") }; Button({ vm.simulate(RideEventType.PASSENGER_PICKED_UP) }) { Text("Pickup") }; Button({ vm.simulate(RideEventType.RIDE_ACTIVE) }) { Text("Verify") }; Button({ vm.simulate(RideEventType.RIDE_COMPLETED) }) { Text("Complete") } } } } } }
@Composable private fun SimplePage(title: String, subtitle: String, modifier: Modifier) { Column(modifier.fillMaxSize().background(OoroBackground).padding(20.dp)) { Text(title, fontSize = 28.sp, fontWeight = FontWeight.SemiBold); Text(subtitle, Modifier.padding(top = 8.dp), color = Color.Gray); Spacer(Modifier.height(20.dp)); Card(Modifier.fillMaxWidth()) { Text("No live backend data connected yet.", Modifier.padding(20.dp), color = Color.Gray) } } }
@Composable private fun RidesContent(dashboard: DashboardState, modifier: Modifier) { LazyColumn(modifier.fillMaxSize().background(OoroBackground).padding(20.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) { item { Text("Rides", fontSize = 28.sp, fontWeight = FontWeight.SemiBold); Text("Only verified passenger rides can generate advertising earnings.", color = Color.Gray) }; val ride = dashboard.activeRide; if (ride == null) item { Card(Modifier.fillMaxWidth()) { Text("No rides recorded yet.", Modifier.padding(20.dp), color = Color.Gray) } } else item { Card(Modifier.fillMaxWidth()) { Column(Modifier.padding(18.dp)) { Text(ride.provider, fontWeight = FontWeight.SemiBold); Text(ride.state.name.replace("_", " "), Modifier.padding(top = 6.dp), color = Color.Gray); Text(if (ride.state == RideState.TO_PICKUP || ride.state == RideState.RIDE_ACCEPTED) "Advertising OFF · Display sleeping" else "Verification and proof-of-play determine payout", Modifier.padding(top = 12.dp), fontSize = 13.sp) } } } } }
@Composable private fun EarningsContent(modifier: Modifier) { Column(modifier.fillMaxSize().background(OoroBackground).padding(20.dp)) { Text("Earnings", fontSize = 28.sp, fontWeight = FontWeight.SemiBold); Text("Ledger-backed earnings and payout history", Modifier.padding(top = 8.dp), color = Color.Gray); Spacer(Modifier.height(16.dp)); Card(Modifier.fillMaxWidth()) { Column(Modifier.padding(18.dp)) { Text("Available balance", color = Color.Gray); Text("₹0", Modifier.padding(top = 6.dp), fontSize = 32.sp, fontWeight = FontWeight.Bold); Text("Verified earnings appear after server reconciliation.", Modifier.padding(top = 8.dp), color = Color.Gray, fontSize = 13.sp) } }; Spacer(Modifier.height(12.dp)); OutlinedButton({}, Modifier.fillMaxWidth()) { Text("Payout setup") } } }
@Composable private fun HelpContent(modifier: Modifier) { Column(modifier.fillMaxSize().background(OoroBackground).padding(20.dp)) { Text("Help & Safety", fontSize = 28.sp, fontWeight = FontWeight.SemiBold); Text("Get help without distracting from driving.", Modifier.padding(top = 8.dp), color = Color.Gray); Spacer(Modifier.height(16.dp)); listOf("Safety / SOS", "Roadside assistance", "Display problem", "Payment problem", "Mobility app detection").forEach { item -> Card(Modifier.fillMaxWidth().padding(vertical = 4.dp)) { Row(Modifier.fillMaxWidth().padding(18.dp), horizontalArrangement = Arrangement.SpaceBetween) { Text(item); Text("›", color = Color.Gray) } } } } }
@Composable private fun ProfileContent(vm: DriverAppViewModel, modifier: Modifier) { Column(modifier.fillMaxSize().background(OoroBackground).padding(20.dp)) { Text("Profile", fontSize = 28.sp, fontWeight = FontWeight.SemiBold); Text("KYC, vehicle, display, permissions and agreements", Modifier.padding(top = 8.dp), color = Color.Gray); Spacer(Modifier.height(16.dp)); listOf("Personal information", "Driver KYC", "Vehicle", "My Display", "Mobility apps", "Permissions", "Privacy", "Agreements").forEach { item -> Card(Modifier.fillMaxWidth().padding(vertical = 4.dp)) { Text(item, Modifier.padding(18.dp)) } }; TextButton({ vm.logout() }, Modifier.padding(top = 12.dp)) { Text("Log out") } } }
