import { config } from '../config.js'
import type { GuestCampaignOrder } from './guest-orders.js'

export type TransactionalEmail = { to: string; subject: string; text: string; html: string }
export interface TransactionalEmailProvider { send(message: TransactionalEmail): Promise<'SENT' | 'SIMULATED'> }
export class LogEmailProvider implements TransactionalEmailProvider { async send(message: TransactionalEmail) { console.info(JSON.stringify({ email: 'SIMULATED', to: message.to, subject: message.subject, text: message.text })); return 'SIMULATED' as const } }
export class ResendEmailProvider implements TransactionalEmailProvider { async send(message: TransactionalEmail) { if (!config.emailProviderApiKey) throw new Error('EMAIL_PROVIDER_API_KEY is not configured'); const response = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { Authorization: `Bearer ${config.emailProviderApiKey}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ from: config.emailFrom, to: [message.to], subject: message.subject, text: message.text, html: message.html }) }); if (!response.ok) throw new Error(`Email provider failed: ${response.status}`); return 'SENT' as const } }
export const emailProvider: TransactionalEmailProvider = config.nodeEnv === 'production' ? new ResendEmailProvider() : new LogEmailProvider()
export async function sendOrderConfirmation(order: GuestCampaignOrder) { const message = { to: order.email, subject: 'OORO — Payment received for your Tirupati campaign', text: `Hi ${order.name},\n\nYour OORO campaign booking has been received.\n\nOrder: ${order.orderNumber}\nCampaign: ${order.city} · ${order.campaignDurationDays} Days · ${order.autos} Autos · ${order.hoursPerDay} Hours / Day\nAmount Paid: ₹${order.amount.toLocaleString('en-IN')}\nPhone: ${order.phone}\n\nOur team will contact you to collect your campaign creative and confirm the launch schedule.\n\nThank you,\nOORO`, html: `<h2>Hi ${escapeHtml(order.name)},</h2><p>Your OORO campaign booking has been received.</p><p><b>Order:</b> ${escapeHtml(order.orderNumber)}<br/><b>Campaign:</b> ${escapeHtml(order.city)} · ${order.campaignDurationDays} Days · ${order.autos} Autos · ${order.hoursPerDay} Hours / Day<br/><b>Amount Paid:</b> ₹${order.amount.toLocaleString('en-IN')}<br/><b>Phone:</b> ${escapeHtml(order.phone)}</p><p>Our team will contact you to collect your campaign creative and confirm the launch schedule.</p><p>Thank you,<br/>OORO</p>` }; return emailProvider.send(message) }
const escapeHtml = (value: string) => value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character] ?? character))
