import type { ReactNode } from "react";
import Link from "next/link";

export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <div className="flex flex-col gap-5 border-b border-neutral-200 pb-8 sm:flex-row sm:items-end sm:justify-between">{<div>{eyebrow && <div className="app-eyebrow">{eyebrow}</div>}<h1 className="mt-2 text-3xl font-medium tracking-[-.04em] sm:text-4xl">{title}</h1>{description && <p className="mt-3 max-w-2xl text-sm leading-6 text-neutral-500">{description}</p>}</div>}{action && <div className="shrink-0">{action}</div>}</div>; }
export function PrimaryButton({ children, href, onClick, type = "button", disabled = false }: { children: ReactNode; href?: string; onClick?: () => void; type?: "button" | "submit"; disabled?: boolean }) { const className = "inline-flex items-center justify-center rounded-[8px] bg-[var(--brand-yellow)] px-4 py-2.5 text-sm font-medium text-black transition hover:-translate-y-px hover:brightness-95 focus:outline-none focus:ring-2 focus:ring-black focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:translate-y-0"; return href ? <Link href={href} className={className}>{children}</Link> : <button type={type} onClick={onClick} disabled={disabled} className={className}>{children}</button>; }
export function SecondaryButton({ children, href, onClick, disabled = false }: { children: ReactNode; href?: string; onClick?: () => void; disabled?: boolean }) { const className = "inline-flex items-center justify-center rounded-[8px] border border-neutral-300 bg-white px-4 py-2.5 text-sm font-medium text-neutral-800 transition hover:border-neutral-500 focus:outline-none focus:ring-2 focus:ring-black focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"; return href ? <Link href={href} className={className}>{children}</Link> : <button type="button" onClick={onClick} disabled={disabled} className={className}>{children}</button>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="border border-dashed border-neutral-300 bg-[#fafaf8] px-6 py-14 text-center"><div className="mx-auto max-w-md"><h2 className="text-lg font-medium">{title}</h2><p className="mt-2 text-sm leading-6 text-neutral-500">{description}</p>{action && <div className="mt-6">{action}</div>}</div></div>; }
export function StatusBadge({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "yellow" }) { return <span className={`inline-flex items-center gap-2 rounded-full border px-2.5 py-1 text-[11px] ${tone === "yellow" ? "border-[#c4df00] bg-[#f3ffb3] text-black" : "border-neutral-200 bg-neutral-100 text-neutral-600"}`}><span className={`h-1.5 w-1.5 rounded-full ${tone === "yellow" ? "bg-black" : "bg-neutral-400"}`}/>{children}</span>; }
export function FormField({ label, name, value, onChange, placeholder, type = "text", required = false }: { label: string; name: string; value?: string; onChange?: (value: string) => void; placeholder?: string; type?: string; required?: boolean }) { return <label className="block text-sm font-medium text-neutral-800">{label}<input name={name} value={value} onChange={event => onChange?.(event.target.value)} placeholder={placeholder} type={type} required={required} className="mt-2 block w-full rounded-[8px] border border-neutral-300 bg-white px-3.5 py-3 text-sm outline-none transition focus:border-black focus:ring-2 focus:ring-black/10"/></label>; }
export function SelectField({ label, name, value, onChange, options }: { label: string; name: string; value?: string; onChange?: (value: string) => void; options: string[] }) { return <label className="block text-sm font-medium text-neutral-800">{label}<select name={name} value={value} onChange={event => onChange?.(event.target.value)} className="mt-2 block w-full rounded-[8px] border border-neutral-300 bg-white px-3.5 py-3 text-sm outline-none focus:border-black focus:ring-2 focus:ring-black/10">{options.map(option => <option key={option}>{option}</option>)}</select></label>; }
export function SectionCard({ title, description, children }: { title: string; description?: string; children: ReactNode }) { return <section className="border border-neutral-200 bg-white p-5 sm:p-7"><div className="mb-6"> <h2 className="text-lg font-medium">{title}</h2>{description && <p className="mt-1 text-sm text-neutral-500">{description}</p>}</div>{children}</section>; }
