import type { ReactNode } from "react";
import Link from "next/link";

export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <div className="flex min-w-0 flex-col gap-5 border-b border-neutral-200 pb-8 sm:flex-row sm:items-end sm:justify-between">{<div className="min-w-0">{eyebrow && <div className="app-eyebrow">{eyebrow}</div>}<h1 className="mt-2 break-words text-3xl font-medium tracking-[-.04em] sm:text-4xl">{title}</h1>{description && <p className="mt-3 max-w-2xl break-words text-sm leading-6 text-neutral-500">{description}</p>}</div>}{action && <div className="max-w-full shrink-0">{action}</div>}</div>; }
export function PrimaryButton({ children, href, onClick, type = "button", disabled = false }: { children: ReactNode; href?: string; onClick?: () => void; type?: "button" | "submit"; disabled?: boolean }) { const className = "inline-flex items-center justify-center rounded-[8px] bg-[var(--brand-yellow)] px-4 py-2.5 text-sm font-medium text-black transition hover:-translate-y-px hover:brightness-95 focus:outline-none focus:ring-2 focus:ring-black focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:translate-y-0"; return href ? <Link href={href} className={className}>{children}</Link> : <button type={type} onClick={onClick} disabled={disabled} className={className}>{children}</button>; }
export function SecondaryButton({ children, href, onClick, disabled = false }: { children: ReactNode; href?: string; onClick?: () => void; disabled?: boolean }) { const className = "inline-flex items-center justify-center rounded-[8px] border border-neutral-300 bg-white px-4 py-2.5 text-sm font-medium text-neutral-800 transition hover:border-neutral-500 focus:outline-none focus:ring-2 focus:ring-black focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"; return href ? <Link href={href} className={className}>{children}</Link> : <button type="button" onClick={onClick} disabled={disabled} className={className}>{children}</button>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="border border-dashed border-neutral-300 bg-[#fafaf8] px-6 py-14 text-center"><div className="mx-auto max-w-md"><h2 className="text-lg font-medium">{title}</h2><p className="mt-2 text-sm leading-6 text-neutral-500">{description}</p>{action && <div className="mt-6">{action}</div>}</div></div>; }
export function StatusBadge({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "yellow" }) { return <span className={`inline-flex items-center gap-2 rounded-full border px-2.5 py-1 text-[11px] ${tone === "yellow" ? "border-[#c4df00] bg-[#f3ffb3] text-black" : "border-neutral-200 bg-neutral-100 text-neutral-600"}`}><span className={`h-1.5 w-1.5 rounded-full ${tone === "yellow" ? "bg-black" : "bg-neutral-400"}`}/>{children}</span>; }
export function FormField({ label, name, value, onChange, placeholder, type = "text", required = false }: { label: string; name: string; value?: string; onChange?: (value: string) => void; placeholder?: string; type?: string; required?: boolean }) { return <label className="block text-sm font-medium text-neutral-800">{label}<input name={name} value={value} onChange={event => onChange?.(event.target.value)} placeholder={placeholder} type={type} required={required} className="mt-2 block w-full rounded-[8px] border border-neutral-300 bg-white px-3.5 py-3 text-sm outline-none transition focus:border-black focus:ring-2 focus:ring-black/10"/></label>; }
export function SelectField({ label, name, value, onChange, options }: { label: string; name: string; value?: string; onChange?: (value: string) => void; options: string[] }) { return <label className="block text-sm font-medium text-neutral-800">{label}<select name={name} value={value} onChange={event => onChange?.(event.target.value)} className="mt-2 block w-full rounded-[8px] border border-neutral-300 bg-white px-3.5 py-3 text-sm outline-none focus:border-black focus:ring-2 focus:ring-black/10">{options.map(option => <option key={option}>{option}</option>)}</select></label>; }
export function SectionCard({ title, description, children }: { title: string; description?: string; children: ReactNode }) { return <section className="border border-neutral-200 bg-white p-5 sm:p-7"><div className="mb-6"> <h2 className="text-lg font-medium">{title}</h2>{description && <p className="mt-1 text-sm text-neutral-500">{description}</p>}</div>{children}</section>; }
export const Card = SectionCard;
export function MetricCard({ label, value, detail }: { label: string; value: ReactNode; detail?: ReactNode }) { return <div className="border border-neutral-200 bg-white p-5"><p className="app-eyebrow">{label}</p><p className="mt-3 text-2xl font-medium tracking-[-.04em]">{value}</p>{detail && <p className="mt-2 text-xs text-neutral-500">{detail}</p>}</div>; }
export function TextareaField({ label, name, value, onChange, placeholder, rows = 4, required = false }: { label: string; name: string; value?: string; onChange?: (value: string) => void; placeholder?: string; rows?: number; required?: boolean }) { return <label className="block text-sm font-medium text-neutral-800">{label}<textarea name={name} value={value} onChange={event => onChange?.(event.target.value)} placeholder={placeholder} rows={rows} required={required} className="mt-2 block w-full resize-y rounded-[8px] border border-neutral-300 bg-white px-3.5 py-3 text-sm outline-none transition focus:border-black focus:ring-2 focus:ring-black/10"/></label>; }
export function LoadingSkeleton({ className = "h-4 w-full" }: { className?: string }) { return <div aria-label="Loading" className={`animate-pulse rounded bg-neutral-200 ${className}`}/>; }
export function ErrorState({ title = "Something went wrong", description = "We could not load this information.", onRetry }: { title?: string; description?: string; onRetry?: () => void }) { return <div role="alert" className="border border-red-200 bg-red-50 px-5 py-8"><p className="font-medium text-red-900">{title}</p><p className="mt-2 text-sm leading-6 text-red-800">{description}</p>{onRetry && <button type="button" onClick={onRetry} className="mt-4 text-sm font-medium text-red-900 underline underline-offset-4">Try again</button>}</div>; }
export function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div role="dialog" aria-modal="true" className="fixed inset-0 z-[60] flex items-center justify-center bg-black/40 p-4" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><div className="w-full max-w-lg border border-neutral-200 bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><h2 className="text-lg font-medium">{title}</h2><button type="button" aria-label="Close" onClick={onClose} className="text-neutral-500 hover:text-black">×</button></div><div className="mt-5">{children}</div></div></div>; }
export function Drawer({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div role="dialog" aria-modal="true" className="fixed inset-0 z-[60] bg-black/30" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><aside className="absolute right-0 top-0 h-full w-full max-w-md overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><h2 className="text-lg font-medium">{title}</h2><button type="button" aria-label="Close" onClick={onClose} className="text-neutral-500 hover:text-black">×</button></div><div className="mt-6">{children}</div></aside></div>; }
export function Tabs({ items, active, onChange }: { items: Array<{ id: string; label: string }>; active: string; onChange: (id: string) => void }) { return <div className="flex gap-5 overflow-x-auto border-b border-neutral-200">{items.map(item => <button type="button" key={item.id} onClick={() => onChange(item.id)} className={`shrink-0 border-b-2 px-1 pb-3 text-sm ${active === item.id ? "border-black font-medium text-black" : "border-transparent text-neutral-500 hover:text-black"}`}>{item.label}</button>)}</div>; }
export function ConfirmDialog({ title, description, confirmLabel = "Confirm", onConfirm, onClose }: { title: string; description: string; confirmLabel?: string; onConfirm: () => void; onClose: () => void }) { return <Modal title={title} onClose={onClose}><p className="text-sm leading-6 text-neutral-600">{description}</p><div className="mt-6 flex justify-end gap-3"><SecondaryButton onClick={onClose}>Cancel</SecondaryButton><button type="button" onClick={onConfirm} className="inline-flex items-center justify-center rounded-[8px] bg-black px-4 py-2.5 text-sm font-medium text-white">{confirmLabel}</button></div></Modal>; }
