"use client";

import { useEffect, useState } from "react";
import { PageHeader, SecondaryButton, StatusBadge } from "./app-ui";

type Campaign = { id: string; name: string; status: string; description?: string | null; startsAt?: string | null; endsAt?: string | null; metadata?: Record<string, unknown>; creatives?: Array<{ asset?: { fileName?: string; mimeType?: string | null; checksum?: string | null } | null }> };

export function BusinessCampaignDetail({ id }: { id: string }) {
  const [campaign, setCampaign] = useState<Campaign | null>(null);
  const [deliverySummary, setDeliverySummary] = useState<{ verifiedPlays?: number; estimatedPassengerImpressions?: number; deliveryProgressPercent?: number } | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void (async () => { try { const campaignResponse = await fetch(`/api/campaigns/${id}`, { cache: "no-store" }); const campaignPayload = await campaignResponse.json(); if (!campaignResponse.ok) throw new Error(campaignPayload?.error?.message || "Campaign could not be loaded"); setCampaign(campaignPayload.data); const deliveryResponse = await fetch(`/api/campaigns/${id}/delivery`, { cache: "no-store" }); const deliveryPayload = await deliveryResponse.json().catch(() => null); if (deliveryResponse.ok) setDeliverySummary(deliveryPayload?.summary ?? null); } catch (caught) { setError(caught instanceof Error ? caught.message : "Campaign could not be loaded"); } })(); }, [id]);
  if (error) return <div className="space-y-5"><PageHeader title="Campaign" action={<SecondaryButton href="/campaigns">Back</SecondaryButton>}/><p role="alert" className="border border-red-200 bg-red-50 p-5 text-sm text-red-800">{error}</p></div>;
  if (!campaign) return <div className="py-16 text-center text-sm text-neutral-500">Loading campaign…</div>;
  const metadata = campaign.metadata ?? {};
  return <div className="space-y-8"><PageHeader eyebrow="Campaign workspace" title={campaign.name} description={campaign.description || "Campaign schedule, creative and verified delivery status."} action={<SecondaryButton href="/campaigns">Back</SecondaryButton>}/><div className="grid gap-6 lg:grid-cols-2"><section className="border border-neutral-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="font-medium">Campaign setup</h2><StatusBadge>{campaign.status.replaceAll("_", " ")}</StatusBadge></div><dl className="mt-6 space-y-4 text-sm"><Row label="Location" value={String(metadata.city || metadata.area || "Not set")}/><Row label="Schedule" value={`${campaign.startsAt || "Not set"} — ${campaign.endsAt || "Not set"}`}/><Row label="Delivery" value={String(metadata.deliveryTier || "Standard")}/><Row label="Budget" value={`₹${String(metadata.budget || "Not set")}`}/></dl></section><section className="border border-neutral-200 bg-white p-6"><h2 className="font-medium">Creative</h2>{campaign.creatives?.length ? campaign.creatives.map((creative, index) => <div className="mt-5 border p-4 text-sm" key={index}>{creative.asset ? <><p className="font-medium">{creative.asset.fileName || "Creative asset"}</p><p className="mt-2 text-xs text-neutral-500">{creative.asset.mimeType || "Unknown type"}</p><p className="mt-2 break-all font-mono text-[10px] text-neutral-400">{creative.asset.checksum || "Checksum unavailable"}</p></> : "Creative asset not available."}</div>) : <p className="mt-5 text-sm text-neutral-500">Not uploaded</p>}</section></div><section className="border border-neutral-200 bg-white p-6"><h2 className="font-medium">Delivery status</h2><p className="mt-2 text-sm text-neutral-500">OORO manages media allocation. Verified playback and modeled passenger impressions are shown below when available.</p><div className="mt-5 grid gap-4 sm:grid-cols-3"><Metric label="Verified plays" value={String(deliverySummary?.verifiedPlays ?? "—")}/><Metric label="Modeled impressions" value={String(deliverySummary?.estimatedPassengerImpressions ?? "—")}/><Metric label="Progress" value={deliverySummary ? `${deliverySummary.deliveryProgressPercent ?? 0}%` : "—"}/></div></section></div>;
}
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b border-neutral-100 pb-3"><dt className="text-neutral-500">{label}</dt><dd className="text-right">{value}</dd></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="border border-neutral-200 p-4"><p className="text-xs text-neutral-500">{label}</p><p className="mt-2 text-2xl font-medium">{value}</p></div>; }
