"use client";
import Link from "next/link";
import { ArrowUpRight, RefreshCw, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { PageHeader, PrimaryButton, StatusBadge } from "./app-ui";

type Campaign = { id: string; name: string; status: string; startsAt?: string | null; endsAt?: string | null; layout?: string | null; metadata?: Record<string, unknown> | null; updatedAt: string };
const date = (value?: string | null) => value ? new Date(value).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "Not scheduled";
export function Campaigns() {
  const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [filter, setFilter] = useState("All"); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const response = await fetch("/api/campaigns", { cache: "no-store" }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error?.message || "Campaigns could not be loaded"); setCampaigns(payload.data ?? []); } catch (caught) { setError(caught instanceof Error ? caught.message : "Campaigns could not be loaded"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const shown = useMemo(() => campaigns.filter(item => (filter === "All" || item.status === filter.toUpperCase()) && item.name.toLowerCase().includes(search.toLowerCase())), [campaigns, filter, search]);
  return <div className="space-y-8"><PageHeader title="Campaigns" description="Plan and manage all offline advertising campaigns." action={<PrimaryButton href="/campaigns/new">Create campaign <ArrowUpRight className="ml-4" size={15}/></PrimaryButton>}/><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-5 overflow-x-auto text-sm text-neutral-500">{["All", "Draft", "Scheduled", "Live", "Completed"].map(item => <button type="button" key={item} onClick={() => setFilter(item)} className={`shrink-0 border-b-2 pb-2 ${filter === item ? "border-black text-black" : "border-transparent"}`}>{item}</button>)}</div><label className="flex items-center gap-2 border-b border-neutral-300 pb-2 text-sm text-neutral-500"><Search size={15}/><span className="sr-only">Search campaigns</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search campaigns" className="w-44 bg-transparent outline-none"/></label></div>{error && <div role="alert" className="flex flex-wrap items-center justify-between gap-3 border border-red-200 bg-red-50 p-4 text-sm text-red-800"><span>{error}</span><button type="button" onClick={() => void load()} className="inline-flex items-center gap-2 font-medium"><RefreshCw size={14}/>Retry</button></div>}{loading ? <div className="border border-neutral-200 bg-white p-12 text-center text-sm text-neutral-500">Loading campaigns…</div> : <div className="overflow-hidden border border-neutral-200 bg-white"><div className="hidden grid-cols-[1.3fr_1fr_1fr_1fr_1fr_auto] gap-4 border-b border-neutral-200 bg-[#fafaf8] px-5 py-3 text-[11px] font-medium text-neutral-500 lg:grid"><span>Campaign</span><span>Media</span><span>Objective</span><span>Location</span><span>Dates</span><span>Status</span></div>{shown.length ? shown.map(item => { const meta = item.metadata ?? {}; return <Link href={`/campaigns/${item.id}`} key={item.id} className="grid gap-3 border-b border-neutral-200 px-5 py-5 transition hover:bg-[#fafaf8] lg:grid-cols-[1.3fr_1fr_1fr_1fr_1fr_auto] lg:items-center lg:gap-4"><div><span className="font-medium">{item.name}</span><span className="mt-1 block font-mono text-[10px] text-neutral-400">{item.id}</span></div><span className="text-sm text-neutral-600">{item.layout || "—"}</span><span className="text-sm text-neutral-600">{String(meta.goal || "—")}</span><span className="text-sm text-neutral-600">{String(meta.area || meta.city || "—")}</span><span className="text-sm text-neutral-600">{item.startsAt ? `${date(item.startsAt)} — ${date(item.endsAt)}` : "Not scheduled"}</span><StatusBadge>{item.status.replaceAll("_", " ")}</StatusBadge></Link>; }) : <div className="p-10 text-center text-sm text-neutral-500">{campaigns.length ? "No campaigns match this view." : "No campaigns yet. Create your first campaign to begin."}</div>}</div>}</div>;
}
