"use client";
import Link from "next/link";
import { ArrowUpRight, FileText, Plus, Upload } from "lucide-react";
import { useState } from "react";
import { brandRepository } from "@/lib/repositories/brand-repository";
import { quoteRepository } from "@/lib/repositories/quote-repository";
import { creativeRepository } from "@/lib/repositories/creative-repository";
import { EmptyState, FormField, PageHeader, PrimaryButton, SectionCard, SecondaryButton, SelectField, StatusBadge } from "./app-ui";

export function Planner() { const [message, setMessage] = useState(""); const [done, setDone] = useState(false); return <div className="mx-auto max-w-3xl space-y-8"><PageHeader eyebrow="Planning workspace" title="Plan with OORO" description="Describe what you're promoting and OORO will help structure the campaign."/><section className="border border-neutral-200 bg-white p-5 sm:p-8"><label className="block text-sm font-medium">What are you planning? <textarea value={message} onChange={event => setMessage(event.target.value)} rows={7} placeholder="We're launching a new café in Koramangala with a ₹40,000 budget and want more store visits." className="mt-3 block w-full resize-none rounded-[8px] border border-neutral-300 bg-[#fafaf8] px-4 py-4 text-sm leading-6 outline-none focus:border-black focus:ring-2 focus:ring-black/10"/></label><div className="mt-6 flex flex-wrap items-center gap-3"><PrimaryButton onClick={() => setDone(true)}>Generate plan <ArrowUpRight className="ml-4" size={15}/></PrimaryButton><SecondaryButton href="/campaigns/new">Build manually →</SecondaryButton></div>{done && <div className="mt-6 border border-dashed border-neutral-300 bg-[#fafaf8] p-5 text-sm"><span className="font-medium">AI planning will be connected after provider setup.</span><p className="mt-2 text-xs text-neutral-500">Your prompt is kept on this page only.</p></div>}</section></div>; }

export function Intelligence() { const [question, setQuestion] = useState(""); const [submitted, setSubmitted] = useState(false); const types = [["Brand Research", "Understand how your brand shows up in a market."], ["Market Research", "Explore the context around a location or category."], ["Audience Research", "Build a clearer picture of who you want to reach."], ["Competitor Research", "Organize the questions you have about competitors."], ["Location Research", "Explore the role a place could play in a campaign."]]; return <div className="space-y-8"><PageHeader eyebrow="Intelligence" title="Research before you plan." description="Keep the questions that shape a better offline campaign in one place."/><div className="border border-neutral-200 bg-white p-5 sm:p-7"><label className="block text-sm font-medium">What do you want to research?<input value={question} onChange={event => setQuestion(event.target.value)} placeholder="Ask about a brand, market, audience or location" className="mt-2 block w-full rounded-[8px] border border-neutral-300 px-3.5 py-3 text-sm outline-none focus:border-black"/></label><button onClick={() => setSubmitted(true)} className="mt-4 rounded-[8px] bg-black px-4 py-2.5 text-sm font-medium text-white">Start with a question →</button>{submitted && <p className="mt-4 text-sm text-neutral-500">Research provider not configured yet.</p>}</div><div className="divide-y border-y border-neutral-200 bg-white">{types.map(([title, description]) => <Link href="/intelligence/research" key={title} className="flex items-center justify-between gap-5 p-5 transition hover:bg-[#fafaf8]"><span><span className="block font-medium">{title}</span><span className="mt-1 block text-sm text-neutral-500">{description}</span></span><ArrowUpRight size={17} className="shrink-0 text-neutral-400"/></Link>)}</div></div>; }

export function Research() { const [started, setStarted] = useState(false); return <div className="mx-auto max-w-3xl space-y-8"><PageHeader eyebrow="Intelligence / Research" title="Start a research brief" description="Capture the question first. Provider connections will come later."/><section className="space-y-6 border border-neutral-200 bg-white p-5 sm:p-8"><FormField label="Research question" name="question" placeholder="What should we understand about this market?"/><SelectField label="Brand" name="brand" options={["Demo brand", "All brands"]}/><FormField label="Market" name="market" placeholder="Bengaluru, India"/><FormField label="Optional source URLs" name="urls" placeholder="https://..."/><PrimaryButton onClick={() => setStarted(true)}>Start research</PrimaryButton>{started && <p className="border-t border-neutral-200 pt-5 text-sm text-neutral-500">Research provider not configured yet.</p>}</section></div>; }

export function Audience() { const [saved, setSaved] = useState(false); const [name, setName] = useState(""); return <div className="space-y-8"><PageHeader title="Audience" description="Create and organize audience definitions for future campaign planning." action={<PrimaryButton onClick={() => setSaved(true)}><Plus className="mr-2" size={15}/>Create audience</PrimaryButton>}/><div className="grid gap-6 lg:grid-cols-[1fr_1fr]"><SectionCard title="Saved audiences"><EmptyState title={saved ? "Audience draft ready." : "No audiences yet."} description="Save a clear audience definition to use in future campaign plans."/></SectionCard><SectionCard title="Audience persona" description="A structured audience editor will appear here."><div className="space-y-4"><FormField label="Name" name="name" value={name} onChange={setName} placeholder="Evening commuters"/><FormField label="Description" name="description" placeholder="People moving through the area after work"/><FormField label="Age range" name="age" placeholder="Optional"/><FormField label="Interests" name="interests" placeholder="Optional"/></div></SectionCard></div></div>; }

export function Creatives() { const [items, setItems] = useState(creativeRepository.list()); const upload = (file: File) => { const creative = { id: crypto.randomUUID(), name: file.name, type: file.type.startsWith("video") ? "Video" as const : "Image" as const, status: "Draft" as const, createdAt: new Date().toISOString() }; creativeRepository.save(creative); setItems(creativeRepository.list()); }; return <div className="space-y-8"><PageHeader title="Creatives" description="Keep the assets you may use in offline campaigns." action={<label className="inline-flex cursor-pointer items-center justify-center rounded-[8px] bg-[var(--brand-yellow)] px-4 py-2.5 text-sm font-medium text-black"><Upload className="mr-2" size={15}/>Upload creative<input type="file" accept="image/*,video/*" className="sr-only" onChange={event => { const file = event.target.files?.[0]; if (file) upload(file); }}/></label>}/><div className="flex gap-5 border-b border-neutral-200 text-sm text-neutral-500"><span className="border-b-2 border-black pb-3 text-black">All</span><span className="pb-3">Images</span><span className="pb-3">Videos</span><span className="pb-3">Approved</span><span className="pb-3">Draft</span></div>{items.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(item => <div className="border border-neutral-200 bg-white p-5" key={item.id}><FileText className="text-neutral-400" size={20}/><p className="mt-7 truncate text-sm font-medium">{item.name}</p><div className="mt-2 flex justify-between text-xs text-neutral-500"><span>{item.type}</span><StatusBadge>{item.status}</StatusBadge></div></div>)}</div> : <EmptyState title="No creatives yet." description="Upload an image or video to start building your creative library."/>}</div>; }

export function AdLab() { const [analyzed, setAnalyzed] = useState(false); const categories = ["Readability", "Brand visibility", "Message clarity", "CTA", "Viewing suitability", "QR readability"]; return <div className="space-y-8"><PageHeader eyebrow="Creative tools" title="Test your creative before it goes live." description="Review the questions OORO will eventually help answer about a creative." action={<SecondaryButton href="/creatives">Choose creative</SecondaryButton>}/><div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="flex min-h-[360px] flex-col items-center justify-center border border-dashed border-neutral-300 bg-[#fafaf8] p-6 text-center"><Upload className="text-neutral-400" size={25}/><p className="mt-4 font-medium">Choose a creative to preview</p><p className="mt-2 text-sm text-neutral-500">Analysis stays inactive until the provider is connected.</p></section><section className="border border-neutral-200 bg-white p-6"><h2 className="font-medium">Creative checks</h2><div className="mt-6 divide-y border-y border-neutral-200">{categories.map(category => <div className="flex items-center justify-between py-4 text-sm" key={category}><span>{category}</span><span className="text-xs text-neutral-400">Not analyzed</span></div>)}</div><button onClick={() => setAnalyzed(true)} className="mt-6 w-full rounded-[8px] bg-black px-4 py-3 text-sm font-medium text-white">Analyze creative</button>{analyzed && <p className="mt-4 text-center text-xs text-neutral-500">Creative analysis will be connected after AI provider setup.</p>}</section></div></div>; }

export function Discover() { const inventory = [["Koramangala", "OORO Auto Screens", "OORO Network"], ["MG Road", "Billboard", "Demo inventory"], ["Indiranagar", "Retail display", "Demo inventory"]]; return <div className="space-y-8"><PageHeader title="Discover media" description="Explore media formats and locations as the OORO network grows."/><div className="flex flex-col gap-4 sm:flex-row"><input placeholder="Search location or media type" className="w-full rounded-[8px] border border-neutral-300 bg-white px-4 py-3 text-sm outline-none focus:border-black"/><div className="flex gap-5 overflow-x-auto text-sm text-neutral-500"><span className="shrink-0 border-b-2 border-black pb-3 text-black">OORO Network</span><span className="shrink-0 pb-3">Billboards</span><span className="shrink-0 pb-3">Digital</span><span className="shrink-0 pb-3">Retail</span></div></div><div className="divide-y border-y border-neutral-200 bg-white">{inventory.map(([area, type, label]) => <div className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between" key={area}><div><div className="flex items-center gap-2"><StatusBadge tone={label === "OORO Network" ? "yellow" : "neutral"}>{label}</StatusBadge></div><h2 className="mt-3 font-medium">{area}</h2><p className="mt-1 text-sm text-neutral-500">{type}</p></div><span className="text-sm text-neutral-500">Demo inventory →</span></div>)}</div></div>; }

export function Locations() { return <div className="space-y-8"><PageHeader title="Locations" description="Save areas and radii to reuse while planning campaigns." action={<PrimaryButton><Plus className="mr-2" size={15}/>Create area</PrimaryButton>}/><div className="grid gap-6 md:grid-cols-2"><SectionCard title="Saved areas"><EmptyState title="No saved areas yet." description="Create an area to keep your planning context close."/></SectionCard><SectionCard title="Recent locations"><p className="text-sm text-neutral-500">Recent locations will appear after you plan a campaign.</p></SectionCard></div></div>; }

export function Analytics() { const metrics = ["Delivery", "Proof of play", "Locations", "Creative performance", "QR interactions", "Conversions"]; return <div className="space-y-8"><PageHeader title="Analytics" description="Understand delivery once campaigns begin running."/><EmptyState title="Analytics will appear once your campaigns start running." description="Future reporting will cover delivery, locations and creative signals without filling this workspace with invented data."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{metrics.map(metric => <div className="border border-neutral-200 bg-white p-5 opacity-60" key={metric}><div className="flex items-center justify-between"><span className="font-medium">{metric}</span><span className="text-xs text-neutral-400">Later</span></div><p className="mt-8 text-sm text-neutral-500">No data yet</p></div>)}</div></div>; }

export function Reports() { return <div className="space-y-8"><PageHeader title="Reports" description="Generated campaign reports will live here."/><EmptyState title="No reports yet." description="Reports become available after campaign delivery data exists." action={<SecondaryButton href="/campaigns">View campaigns</SecondaryButton>}/><div className="grid gap-4 md:grid-cols-3">{["Campaign report", "Delivery report", "Creative report"].map(item => <div className="border border-neutral-200 bg-white p-5" key={item}><FileText className="text-neutral-400" size={20}/><h2 className="mt-6 text-sm font-medium">{item}</h2><p className="mt-2 text-xs text-neutral-500">Not available yet.</p></div>)}</div></div>; }

export function Brands() { const [brands, setBrands] = useState(brandRepository.list()); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const save = () => { if (!name.trim()) return; brandRepository.save({ id: crypto.randomUUID(), name, website: "", industry: "", market: "" }); setBrands(brandRepository.list()); setName(""); setOpen(false); }; return <div className="space-y-8"><PageHeader title="Brands & Clients" description="Manage the brands and client contexts you plan media for." action={<PrimaryButton onClick={() => setOpen(true)}><Plus className="mr-2" size={15}/>Add brand</PrimaryButton>}/><div className="overflow-hidden border border-neutral-200 bg-white"><div className="hidden grid-cols-[1.2fr_1fr_1fr_1fr_auto] gap-4 border-b border-neutral-200 bg-[#fafaf8] px-5 py-3 text-[11px] text-neutral-500 sm:grid"><span>Brand name</span><span>Website</span><span>Industry</span><span>Primary market</span><span>Status</span></div>{brands.map(brand => <div className="grid gap-3 border-b border-neutral-200 px-5 py-5 sm:grid-cols-[1.2fr_1fr_1fr_1fr_auto] sm:items-center sm:gap-4" key={brand.id}><span className="font-medium">{brand.name}</span><span className="text-sm text-neutral-500">{brand.website || "Not added"}</span><span className="text-sm text-neutral-500">{brand.industry || "Not added"}</span><span className="text-sm text-neutral-500">{brand.market || "Not added"}</span><StatusBadge>Active workspace</StatusBadge></div>)}</div>{open && <div className="border border-neutral-300 bg-white p-5 sm:p-7"><div className="flex items-center justify-between"><h2 className="font-medium">Add brand</h2><button onClick={() => setOpen(false)} className="text-sm text-neutral-500">Close</button></div><div className="mt-5 max-w-xl"><FormField label="Brand name" name="name" value={name} onChange={setName} placeholder="Brand name"/><div className="mt-5"><PrimaryButton onClick={save}>Save brand</PrimaryButton></div></div></div>}</div>; }

export function Quotes() { const [quotes, setQuotes] = useState(quoteRepository.list()); const [open, setOpen] = useState(false); return <div className="space-y-8"><PageHeader title="Quotes" description="Request custom media planning support when standard inventory is not enough." action={<PrimaryButton onClick={() => setOpen(true)}><Plus className="mr-2" size={15}/>Request quote</PrimaryButton>}/><div className="flex gap-5 overflow-x-auto border-b border-neutral-200 text-sm text-neutral-500">{["Draft", "Requested", "Sent", "Approved", "Expired"].map(item => <span className="shrink-0 pb-3 first:border-b-2 first:border-black first:text-black" key={item}>{item}</span>)}</div>{quotes.length ? quotes.map(quote => <div className="border border-neutral-200 bg-white p-5" key={quote.id}>{quote.brand} · {quote.campaign}</div>) : <EmptyState title="No quotes yet." description="Request a quote when you need help planning custom physical media."/>}{open && <section className="border border-neutral-200 bg-white p-6"><h2 className="font-medium">Request a quote</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><FormField label="Brand" name="brand" placeholder="Demo brand"/><FormField label="Campaign" name="campaign" placeholder="Campaign name"/><FormField label="Budget" name="budget" placeholder="Optional"/><FormField label="Locations" name="locations" placeholder="Bengaluru areas"/></div><div className="mt-5 flex gap-3"><PrimaryButton onClick={() => { setQuotes(quoteRepository.list()); setOpen(false); }}>Save request</PrimaryButton><SecondaryButton onClick={() => setOpen(false)}>Cancel</SecondaryButton></div></section>}</div>; }

export function Team() { return <div className="space-y-8"><PageHeader title="Team" description="Manage workspace access for the people planning media with you." action={<PrimaryButton><Plus className="mr-2" size={15}/>Invite member</PrimaryButton>}/><EmptyState title="You are the only member for now." description="Invitations and role-based access will be connected later."/><SectionCard title="Available roles"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["Owner", "Admin", "Member", "Viewer"].map(role => <div className="border border-neutral-200 p-4" key={role}><span className="font-medium">{role}</span><p className="mt-2 text-xs leading-5 text-neutral-500">Role permissions will be configurable later.</p></div>)}</div></SectionCard></div>; }

export function Billing() { return <div className="space-y-8"><PageHeader title="Billing" description="Billing and spend controls will connect after the payment setup is finalized."/><div className="grid gap-6 md:grid-cols-2"><SectionCard title="Payment method"><p className="text-sm text-neutral-500">Billing setup will be connected later.</p></SectionCard><SectionCard title="Campaign spend"><p className="text-sm text-neutral-500">No campaign spend to show.</p></SectionCard><SectionCard title="Invoices"><p className="text-sm text-neutral-500">No invoices yet.</p></SectionCard><SectionCard title="Credits"><p className="text-sm text-neutral-500">Credits will appear after billing is connected.</p></SectionCard></div></div>; }

export function Settings() { const [name, setName] = useState("OORO Workspace"); const [type, setType] = useState("Marketing Agency"); const [saved, setSaved] = useState(false); return <div className="space-y-8"><PageHeader title="Settings" description="Manage workspace preferences without changing your local data."/><div className="grid gap-6 lg:grid-cols-[220px_1fr]"><nav className="space-y-1 text-sm text-neutral-500">{["Workspace", "Profile", "Brands", "Notifications", "Security", "Preferences"].map((item, index) => <div className={`rounded px-3 py-2 ${index === 0 ? "bg-black text-white" : ""}`} key={item}>{item}</div>)}</nav><SectionCard title="Workspace" description="These values are saved locally in this browser."><div className="max-w-xl space-y-5"><FormField label="Workspace name" name="workspace" value={name} onChange={setName}/><SelectField label="Workspace type" name="type" value={type} onChange={setType} options={["Brand / Company", "Small Business", "Marketing Agency", "Individual"]}/><PrimaryButton onClick={() => setSaved(true)}>{saved ? "Saved locally" : "Save changes"}</PrimaryButton></div></SectionCard></div></div>; }
