"use client";
import { FormEvent, useMemo, useState } from "react";
import { normalizeIndianPhone } from "@/apps/api/src/domain/phone";
import { apiUrl } from "@/lib/api-url";

type Plan = { id: string; autos: number; hoursPerDay: 4 | 8; amount: number; city: string; durationDays: number };
const plans: Plan[] = [
  ...([5, 10, 15, 25] as const).map((autos, i) => ({ id: `TPT_30D_4H_${autos}`, autos, hoursPerDay: 4 as const, amount: [3000, 6000, 9000, 15000][i], city: "Tirupati", durationDays: 30 })),
  ...([5, 10, 15, 25] as const).map((autos, i) => ({ id: `TPT_30D_8H_${autos}`, autos, hoursPerDay: 8 as const, amount: [5000, 10000, 15000, 25000][i], city: "Tirupati", durationDays: 30 })),
];
export function CampaignPricing() { const [hours, setHours] = useState<4 | 8>(4); const [selected, setSelected] = useState<Plan | null>(null); const visible = useMemo(() => plans.filter(p => p.hoursPerDay === hours), [hours]); return <section id="campaign-pricing" className="border-y border-white/10 bg-[#0b0b0b] py-20 text-white"><div className="container-ooro"><span className="eyebrow text-neutral-500">Tirupati launch pricing · 30-day campaign</span><div className="mt-5 flex flex-col justify-between gap-8 md:flex-row md:items-end"><h2 className="display max-w-2xl text-5xl font-medium sm:text-6xl">Put your brand<br/><span className="text-[var(--brand-yellow)]">in motion.</span></h2><p className="max-w-sm text-sm leading-6 text-neutral-400">Choose your daily reach. No account required—just your campaign details and a secure checkout.</p></div><div className="mt-10 inline-flex rounded-full border border-white/15 p-1">{([4, 8] as const).map(value => <button key={value} onClick={() => setHours(value)} className={`rounded-full px-5 py-2 text-sm ${hours === value ? "bg-[var(--brand-yellow)] text-black" : "text-neutral-400"}`}>{value} Hours / Day</button>)}</div><div className="mt-8 grid gap-px border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{visible.map(plan => <div key={plan.id} className="bg-[#0b0b0b] p-6"><p className="text-sm text-neutral-400">{plan.autos} autos</p><p className="mt-6 text-3xl font-medium">₹{plan.amount.toLocaleString("en-IN")}</p><p className="mt-2 text-xs text-neutral-500">{plan.hoursPerDay} hours/day · 30 days</p><button onClick={() => setSelected(plan)} className="mt-8 w-full rounded-[7px] bg-white px-4 py-3 text-sm font-medium text-black hover:bg-[var(--brand-yellow)]">Book campaign</button></div>)}</div></div>{selected && <Checkout plan={selected} close={() => setSelected(null)}/>}</section> }

function Checkout({ plan, close }: { plan: Plan; close: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy) return; setBusy(true); setError("");
    const data = Object.fromEntries(new FormData(event.currentTarget));
    const phone = normalizeIndianPhone(String(data.phone ?? ""));
    if (!phone) { setError("Enter a valid 10-digit Indian mobile number"); setBusy(false); return; }
    try {
      const response = await fetch(`${apiUrl}/api/public/campaign-orders`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, phone, packageId: plan.id }) });
      const result = await response.json() as { data?: { orderNumber: string; razorpayOrderId: string; keyId: string; amount: number; currency: string; name: string; email: string; phone: string }; error?: { code?: string; message?: string } };
      if (!response.ok || !result.data) { const code = result.error?.code; if (code === "INVALID_PHONE") throw new Error("Enter a valid 10-digit Indian mobile number"); if (code === "INVALID_PACKAGE") throw new Error("This package is no longer available."); if (code === "PAYMENT_PROVIDER_NOT_CONFIGURED" || code === "PAYMENT_PROVIDER_UNAVAILABLE") throw new Error("Payment setup is temporarily unavailable. Please try again shortly."); throw new Error(result.error?.message ?? "Could not start checkout."); }
      const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js";
      script.onerror = () => { setError("Secure checkout could not be loaded. Please try again."); setBusy(false); };
      script.onload = () => { const checkout = new (window as typeof window & { Razorpay: new (options: Record<string, unknown>) => { open: () => void } }).Razorpay({ key: result.data!.keyId, amount: result.data!.amount, currency: result.data!.currency, name: "OORO", description: `${plan.city} · ${plan.autos} autos · ${plan.hoursPerDay} hours/day`, order_id: result.data!.razorpayOrderId, prefill: { name: result.data!.name, email: result.data!.email, contact: result.data!.phone }, handler: async (payment: { razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string }) => { try { const verified = await fetch(`${apiUrl}/api/public/campaign-orders/verify`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ orderNumber: result.data!.orderNumber, razorpayOrderId: payment.razorpay_order_id, razorpayPaymentId: payment.razorpay_payment_id, razorpaySignature: payment.razorpay_signature }) }); if (!verified.ok) throw new Error("Payment verification failed"); window.location.href = `/payment/success/${result.data!.orderNumber}`; } catch (caught) { setError(caught instanceof Error ? caught.message : "Payment verification failed."); setBusy(false); } } }); checkout.open(); };
      document.body.appendChild(script);
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not start checkout."); setBusy(false); }
  }
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/80 p-4"><div className="mx-auto mt-8 max-w-lg bg-[#f7f7f4] p-6 text-black sm:p-8"><div className="flex items-start justify-between"><div><p className="eyebrow text-neutral-500">{plan.city} · {plan.durationDays} days</p><h3 className="mt-3 text-2xl font-medium">Your campaign details</h3><p className="mt-2 text-sm text-neutral-500">{plan.autos} autos · {plan.hoursPerDay} hours/day · ₹{plan.amount.toLocaleString("en-IN")}</p></div><button onClick={close} className="text-2xl text-neutral-400" aria-label="Close">×</button></div><form onSubmit={submit} className="mt-7 space-y-4"><input required name="name" placeholder="Full name" className="w-full border border-neutral-300 bg-white p-3 text-sm"/><input required type="email" name="email" placeholder="Email address" className="w-full border border-neutral-300 bg-white p-3 text-sm"/><input required name="phone" type="tel" placeholder="+91 98765 43210" autoComplete="tel" className="w-full border border-neutral-300 bg-white p-3 text-sm"/><input required name="businessName" placeholder="Business / brand name" className="w-full border border-neutral-300 bg-white p-3 text-sm"/><input name="gstin" placeholder="GSTIN (optional)" className="w-full border border-neutral-300 bg-white p-3 text-sm"/><textarea name="campaignNotes" placeholder="Campaign notes (optional)" rows={3} className="w-full border border-neutral-300 bg-white p-3 text-sm"/><p className="text-xs leading-5 text-neutral-500">By continuing, you agree to OORO&apos;s Terms and Privacy Policy and consent to being contacted about this campaign purchase.</p>{error && <p className="text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-[7px] bg-black px-4 py-3.5 text-sm font-medium text-white disabled:opacity-50">{busy ? "Preparing secure payment…" : `Continue to pay ₹${plan.amount.toLocaleString("en-IN")}`}</button></form></div></div>;
}
