import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { webPrisma } from "@/lib/web-prisma";
import { webOwnerEmail } from "@/lib/web-owner";
import { dateKeys, slotCandidates } from "@/apps/api/src/domain/inventory";
import { selfServeServiceability } from "@/apps/api/src/domain/self-serve-serviceability";

export async function POST(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const ownerEmail = await webOwnerEmail(); if (!ownerEmail) return NextResponse.json({ error: { message: "Sign in to hold inventory" } }, { status: 401 }); const { id } = await params;
  try {
    const campaign = await webPrisma.campaign.findFirst({ where: { id, ownerEmail }, include: { assignments: { where: { active: true }, select: { displayId: true } } } });
    if (!campaign || !campaign.startsAt || !campaign.endsAt) return NextResponse.json({ error: { message: "Campaign schedule is required before holding inventory" } }, { status: 422 });
    const serviceability = campaign.campaignCenterLat !== null && campaign.campaignCenterLng !== null && campaign.radiusKm !== null ? selfServeServiceability(campaign.campaignCenterLat, campaign.campaignCenterLng, campaign.radiusKm) : null;
    if (serviceability?.availability === "UNSUPPORTED") return NextResponse.json({ error: { message: "OORO does not currently offer campaign delivery in this location" } }, { status: 422 });
    const now = new Date(); await webPrisma.inventoryAllocation.updateMany({ where: { status: "HELD", expiresAt: { lt: now } }, data: { status: "CANCELLED", expiresAt: null } });
    const existing = await webPrisma.inventoryAllocation.findFirst({ where: { campaignId: id, status: "HELD", OR: [{ expiresAt: null }, { expiresAt: { gt: now } }] } }); if (existing) return NextResponse.json({ data: { holdId: existing.holdId, expiresAt: existing.expiresAt, status: "INVENTORY_HELD" } });
    const setting = await webPrisma.forecastSetting.findUnique({ where: { key: "DEFAULT" } }); const expiresAt = new Date(now.getTime() + (setting?.inventoryHoldMinutes ?? 15) * 60_000); const holdId = randomUUID(); const tier = campaign.deliveryTier === "PREMIUM_PLUS" ? "PREMIUM_PLUS" : "STANDARD";
    if (!campaign.assignments.length) return NextResponse.json({ data: { holdId: `planned-${holdId}`, expiresAt: null, status: "PLANNED_DELIVERY_COMMITMENT", allocationMode: "PLANNED_DELIVERY_COMMITMENT" } }, { status: 201 });
    await webPrisma.$transaction(async tx => { const dates = dateKeys(campaign.startsAt!, campaign.endsAt!); for (const assignment of campaign.assignments) { const config = await tx.screenInventoryConfig.upsert({ where: { screenId: assignment.displayId }, update: {}, create: { screenId: assignment.displayId } }); for (const date of dates) { const occupied = await tx.inventoryAllocation.findMany({ where: { screenId: assignment.displayId, date: new Date(`${date}T00:00:00.000Z`), status: { in: ["HELD", "RESERVED", "ACTIVE", "BLOCKED"] } }, select: { slot: true } }); const used = new Set(occupied.map(item => item.slot)); const slot = slotCandidates(Math.min(config.totalSlots, config.commercialSlots + config.houseSlots + config.blockedSlots), config.premiumSlots, tier).find(candidate => candidate < config.commercialSlots && !used.has(candidate)); if (slot === undefined) throw new Error("INVENTORY_HOLD_FAILED"); await tx.inventoryAllocation.create({ data: { campaignId: id, screenId: assignment.displayId, date: new Date(`${date}T00:00:00.000Z`), slot, holdId, expiresAt, status: "HELD", rate: campaign.effectiveRate, pricingSource: campaign.pricingSource ?? tier } }); } } });
    return NextResponse.json({ data: { holdId, expiresAt, status: "INVENTORY_HELD" } }, { status: 201 });
  } catch (error) { const message = error instanceof Error ? error.message : "unknown"; console.warn("INVENTORY_HOLD_FAILED", message); if (message === "INVENTORY_HOLD_FAILED") { const campaign = await webPrisma.campaign.findFirst({ where: { id }, select: { campaignCenterLat: true, campaignCenterLng: true, radiusKm: true } }); const latitude = campaign?.campaignCenterLat; const longitude = campaign?.campaignCenterLng; const radius = campaign?.radiusKm; const supported = latitude !== null && latitude !== undefined && longitude !== null && longitude !== undefined && radius !== null && radius !== undefined && selfServeServiceability(latitude, longitude, radius).availability !== "UNSUPPORTED"; if (supported) return NextResponse.json({ data: { holdId: `planned-${randomUUID()}`, expiresAt: null, status: "PLANNED_DELIVERY_COMMITMENT", allocationMode: "PLANNED_DELIVERY_COMMITMENT" } }, { status: 201 }); } return NextResponse.json({ error: { message: "Selected inventory could not be held. Change dates or targeting and try again." } }, { status: 409 }); }
}

export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) { const ownerEmail = await webOwnerEmail(); if (!ownerEmail) return NextResponse.json({ error: { message: "Sign in to release inventory" } }, { status: 401 }); const { id } = await params; try { const result = await webPrisma.inventoryAllocation.updateMany({ where: { campaignId: id, status: "HELD" }, data: { status: "CANCELLED", expiresAt: null } }); return NextResponse.json({ data: { released: result.count } }); } catch { return NextResponse.json({ error: { message: "Inventory hold could not be released" } }, { status: 503 }); } }

export async function PATCH(_request: Request, { params }: { params: Promise<{ id: string }> }) { const ownerEmail = await webOwnerEmail(); if (!ownerEmail) return NextResponse.json({ error: { message: "Sign in to confirm inventory" } }, { status: 401 }); const { id } = await params; try { const campaign = await webPrisma.campaign.findFirst({ where: { id, ownerEmail } }); if (!campaign) return NextResponse.json({ error: { message: "Campaign not found" } }, { status: 404 }); const result = await webPrisma.inventoryAllocation.updateMany({ where: { campaignId: id, status: "HELD", OR: [{ expiresAt: null }, { expiresAt: { gt: new Date() } }] }, data: { status: "RESERVED", expiresAt: null } }); if (result.count === 0) return NextResponse.json({ error: { message: "Inventory hold has expired" } }, { status: 409 }); return NextResponse.json({ data: { status: "ALLOCATION_CONFIRMED", allocations: result.count } }); } catch (error) { console.warn("PAYMENT_SUCCESS_ALLOCATION_FAILED", error instanceof Error ? error.message : "unknown"); return NextResponse.json({ error: { message: "Payment was received but inventory confirmation requires operations review" } }, { status: 409 }); } }
