ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "WebAccount" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "WebAccount" ADD COLUMN IF NOT EXISTS "onboardingStatus" TEXT NOT NULL DEFAULT 'NOT_STARTED';
ALTER TABLE "WebAccount" ADD COLUMN IF NOT EXISTS "onboardingStep" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "WebAccount" ADD COLUMN IF NOT EXISTS "onboardingCompletedAt" TIMESTAMP(3);
ALTER TABLE "WebAccount" ADD COLUMN IF NOT EXISTS "onboardingData" JSONB;
