"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { PageHeader, SectionCard } from "@/components/app/app-ui";
import { AdminSubnav, ConnectivityStatus, HealthBanner, HealthSeverityIcon, PlayerState, RelativeTime, StorageStatus } from "./admin-ui";
import { deviceHealthRepository, isMockDeviceData, screenRepository } from "@/lib/admin/repositories";
import type { DeviceHealth, Screen } from "@/lib/admin/types";

export function DeviceHealthPage() {
  const [screens, setScreens] = useState<Screen[]>([]); const [health, setHealth] = useState<DeviceHealth[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = () => { setLoading(true); setError(""); Promise.all([screenRepository.listScreens(), deviceHealthRepository.getFleetHealth()]).then(([items, fleet]) => { setScreens(items); setHealth(fleet.screens); }).catch(() => setError("Unable to load device health. Check the connection and retry.")).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const byScreen = new Map(health.map(item => [item.screenId, item])); const summary = health.length ? { healthy: health.filter(item => !item.issues.some(issue => issue.severity === "WARNING" || issue.severity === "CRITICAL")).length, attention: health.filter(item => item.issues.some(issue => issue.severity === "WARNING")).length, offline: health.filter(item => item.connectivity === "OFFLINE").length, storage: health.filter(item => item.storageHealth === "LOW" || item.storageHealth === "CRITICAL").length, manifest: health.filter(item => item.manifestVersion === undefined).length, kiosk: health.filter(item => item.kioskActive === false || item.deviceOwner === false).length } : { healthy: 0, attention: 0, offline: 0, storage: 0, manifest: 0, kiosk: 0 };
  return <div className="space-y-7"><PageHeader eyebrow="Admin / Device Health" title="Device Health" description="Monitor connectivity, playback and device health across the OORO network."/><HealthBanner mock={isMockDeviceData}/><AdminSubnav/><div className="grid grid-cols-2 gap-px overflow-hidden border border-neutral-200 bg-neutral-200 sm:grid-cols-3 lg:grid-cols-6">{[["Healthy", summary.healthy], ["Needs attention", summary.attention], ["Offline", summary.offline], ["Low storage", summary.storage], ["Manifest issues", summary.manifest], ["Kiosk issues", summary.kiosk]].map(([label, value]) => <div className="bg-white p-4" key={String(label)}><p className="app-eyebrow">{label}</p><p className="mt-3 text-xl font-medium">{value}</p></div>)}</div><SectionCard title="Fleet health" description="Severity is derived from reported heartbeat state and centralized health thresholds.">{error ? <div className="flex items-center justify-between gap-4 py-12 text-sm"><span className="text-red-700">{error}</span><button type="button" onClick={load} className="underline underline-offset-4">Retry</button></div> : loading ? <div className="py-12 text-center text-sm text-neutral-500">Loading device health…</div> : screens.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-y border-neutral-200 text-[10px] uppercase tracking-[.12em] text-neutral-400">{["Screen", "Health", "Connectivity", "Heartbeat", "Player", "Storage", "Network", "App", "Manifest"].map(label => <th className="px-3 py-3 font-medium first:pl-0" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y divide-neutral-100">{screens.map(screen => <HealthRow key={screen.screenId} screen={screen} health={byScreen.get(screen.screenId)}/>)}</tbody></table></div> : <div className="py-12 text-center text-sm text-neutral-500">No heartbeat data is connected yet.</div>}</SectionCard></div>;
}
function HealthRow({ screen, health }: { screen: Screen; health?: DeviceHealth }) { const critical = health?.issues.some(issue => issue.severity === "CRITICAL"); const warning = health?.issues.some(issue => issue.severity === "WARNING"); return <tr><td className="px-3 py-4 pl-0"><Link href={`/admin/screens/${screen.screenId}`} className="font-medium hover:underline">{screen.screenName}</Link><span className="mt-1 block text-[11px] text-neutral-400">{screen.area} · {screen.city}</span></td><td className="px-3 py-4"><span className="flex items-center gap-2 text-xs font-medium"><HealthSeverityIcon severity={critical ? "CRITICAL" : warning ? "WARNING" : health ? "HEALTHY" : "INFO"}/>{critical ? "Critical" : warning ? "Needs attention" : health ? "Healthy" : "Waiting"}</span></td><td className="px-3 py-4"><ConnectivityStatus status={health?.connectivity ?? "NEVER_CONNECTED"}/></td><td className="px-3 py-4 text-xs"><RelativeTime value={health?.timestamp}/></td><td className="px-3 py-4"><PlayerState state={health?.playerState}/></td><td className="px-3 py-4"><StorageStatus free={health?.freeStorageBytes} total={health?.totalStorageBytes}/></td><td className="px-3 py-4 text-xs">{health?.networkType ?? "—"}</td><td className="px-3 py-4 text-xs">{health?.appVersion ?? "—"}</td><td className="px-3 py-4 text-xs">{health?.manifestVersion ? `v${health.manifestVersion}` : "—"}</td></tr>; }
