"use client";
import Link from "next/link";
import { ArrowLeft, Copy, RefreshCw } from "lucide-react";
import { FormEvent, useState } from "react";
import { PageHeader, PrimaryButton, SecondaryButton, SelectField } from "@/components/app/app-ui";
import { AdminSubnav } from "./admin-ui";
import { pairingRepository, screenRepository, isMockDeviceData } from "@/lib/admin/repositories";
import type { PairingCode, ScreenType } from "@/lib/admin/types";

export function NewScreenPage() {
  const [code, setCode] = useState<PairingCode | null>(null); const [screenId, setScreenId] = useState<string | null>(null); const [error, setError] = useState(""); const [copied, setCopied] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); const screen = await screenRepository.createScreen({ screenName: String(data.get("screenName") || ""), screenType: String(data.get("screenType")) as ScreenType, city: String(data.get("city") || ""), area: String(data.get("area") || ""), vehicleId: String(data.get("vehicleId") || "") || undefined, inventoryId: String(data.get("inventoryId") || "") || undefined, notes: String(data.get("notes") || "") || undefined }); if (!isMockDeviceData || screen.screenId === "unavailable") { setError("Screen creation is not connected to the API yet. Enable explicit mock mode for pilot UI testing."); return; } setScreenId(screen.screenId); setCode(await pairingRepository.createCode(screen.screenId)); }
  async function regenerate() { if (screenId) setCode(await pairingRepository.createCode(screenId)); }
  async function copyCode() { if (!code) return; await navigator.clipboard?.writeText(code.code); setCopied(true); window.setTimeout(() => setCopied(false), 1500); }
  if (code) return <div className="space-y-7"><PageHeader eyebrow="Admin / Screens / New" title="Connect this screen" description="Enter this one-time code on the OORO Screen Player. Pairing codes are mock-only until the backend is connected." action={<Link href="/admin/screens" className="inline-flex items-center gap-2 text-sm text-neutral-500 hover:text-black"><ArrowLeft size={15}/>Back to screens</Link>}/><div className="mx-auto max-w-xl border border-neutral-200 bg-white p-7 text-center sm:p-12"><div className="app-eyebrow">Setup code</div><p className="mt-6 font-mono text-5xl font-medium tracking-[.22em]">{code.code}</p><p className="mt-5 text-sm leading-6 text-neutral-500">Expires {new Date(code.expiresAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}. Enter it on the Android screen to connect.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><SecondaryButton onClick={copyCode}><Copy size={14} className="mr-2"/>{copied ? "Copied" : "Copy code"}</SecondaryButton><SecondaryButton onClick={regenerate}><RefreshCw size={14} className="mr-2"/>Regenerate</SecondaryButton></div><div className="mt-10 border-t border-neutral-200 pt-6 text-left"><p className="text-sm font-medium">Pairing state</p><p className="mt-1 text-sm text-neutral-500">Waiting for the device to submit this code.</p></div><div className="mt-6"><PrimaryButton href={`/admin/screens/${screenId}`}>View screen</PrimaryButton></div></div></div>;
  return <div className="space-y-7"><PageHeader eyebrow="Admin / Screens / New" title="Add screen" description="Create display inventory, then generate a one-time setup code for the installer." action={<Link href="/admin/screens" className="inline-flex items-center gap-2 text-sm text-neutral-500 hover:text-black"><ArrowLeft size={15}/>Back to screens</Link>}/><AdminSubnav/><form onSubmit={submit} className="max-w-3xl border border-neutral-200 bg-white p-5 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Screen name<input required name="screenName" placeholder="Screen 014" className="mt-2 block w-full rounded-[8px] border border-neutral-300 px-3.5 py-3 text-sm outline-none focus:border-black"/></label><SelectField label="Screen type" name="screenType" options={["AUTO_SCREEN", "CAB_SCREEN", "RETAIL_SCREEN", "BILLBOARD_SCREEN", "OTHER"]}/><label className="text-sm font-medium">City<input required name="city" placeholder="Bengaluru" className="mt-2 block w-full rounded-[8px] border border-neutral-300 px-3.5 py-3 text-sm outline-none focus:border-black"/></label><label className="text-sm font-medium">Area<input required name="area" placeholder="Koramangala" className="mt-2 block w-full rounded-[8px] border border-neutral-300 px-3.5 py-3 text-sm outline-none focus:border-black"/></label><label className="text-sm font-medium">Vehicle ID <span className="font-normal text-neutral-400">optional</span><input name="vehicleId" placeholder="KA-01-AB-014" className="mt-2 block w-full rounded-[8px] border border-neutral-300 px-3.5 py-3 text-sm outline-none focus:border-black"/></label><label className="text-sm font-medium">Inventory reference <span className="font-normal text-neutral-400">optional</span><input name="inventoryId" placeholder="INV-014" className="mt-2 block w-full rounded-[8px] border border-neutral-300 px-3.5 py-3 text-sm outline-none focus:border-black"/></label><label className="text-sm font-medium sm:col-span-2">Internal notes <span className="font-normal text-neutral-400">optional</span><textarea name="notes" rows={4} placeholder="Installation or operational notes" className="mt-2 block w-full resize-y rounded-[8px] border border-neutral-300 px-3.5 py-3 text-sm outline-none focus:border-black"/></label></div>{error && <p role="alert" className="mt-5 text-sm text-red-700">{error}</p>}<div className="mt-8 flex justify-end border-t border-neutral-200 pt-5"><PrimaryButton type="submit">Create screen</PrimaryButton></div></form></div>;
}
