"use client";
import { FormEvent, useEffect, useState } from "react";

export function AdminAuthForm() {
  const [phone, setPhone] = useState(""); const [code, setCode] = useState(""); const [requested, setRequested] = useState(false); const [devOtp, setDevOtp] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; fetch("/api/auth/admin").then(async response => { if (response.ok) { window.location.href = new URLSearchParams(window.location.search).get("next") || "/admin"; return; } if (response.status !== 401 && active) setError("Unable to check admin session."); }).catch(() => { if (active) setError("Unable to check admin session."); }); return () => { active = false; }; }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); const endpoint = requested ? "/api/auth/admin/verify-otp" : "/api/auth/admin/request-otp"; const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(requested ? { phone, code } : { phone }) }); const payload = await response.json().catch(() => null); setBusy(false); if (!response.ok) return setError(payload?.error?.message || "Unable to authenticate admin account."); if (!requested) { setRequested(true); setDevOtp(payload?.data?.devOtp || ""); return; } window.location.href = new URLSearchParams(window.location.search).get("next") || "/admin/screens"; }
  return <form onSubmit={submit} className="space-y-5"><label className="block text-sm font-medium">Admin phone<input required value={phone} onChange={event => setPhone(event.target.value)} disabled={requested} placeholder="+91..." className="mt-2 block w-full rounded-[9px] border border-neutral-300 bg-white px-4 py-3 text-sm outline-none focus:border-black"/></label>{requested && <label className="block text-sm font-medium">One-time password<input required minLength={6} maxLength={6} value={code} onChange={event => setCode(event.target.value)} placeholder="6-digit OTP" className="mt-2 block w-full rounded-[9px] border border-neutral-300 bg-white px-4 py-3 text-sm outline-none focus:border-black"/>{devOtp && <span className="mt-2 block text-xs text-neutral-500">Development OTP: {devOtp}</span>}</label>}{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-[9px] bg-black px-4 py-3.5 text-sm font-medium text-white disabled:opacity-60">{busy ? "Working…" : requested ? "Verify admin access" : "Send admin OTP"}</button></form>;
}
