import { NextResponse } from "next/server";
import { z } from "zod";
import { AdminAuthError, getAuthenticatedAdmin } from "@/lib/auth/backend-session";
import { webPrisma } from "@/lib/web-prisma";

export const dynamic = "force-dynamic";
const createSchema = z.object({ name: z.string().trim().min(1), advertiser: z.string().trim().optional(), campaignType: z.literal("INTERNAL_TEST").default("INTERNAL_TEST"), startDate: z.string().optional(), endDate: z.string().optional(), startTime: z.string().regex(/^\d{2}:\d{2}$/).default("08:00"), endTime: z.string().regex(/^\d{2}:\d{2}$/).default("22:00"), days: z.array(z.string()).default(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]), timezone: z.string().default("Asia/Kolkata"), frequency: z.enum(["LOW", "NORMAL", "HIGH", "PRIORITY"]).default("NORMAL"), playsPerLoop: z.number().int().min(1).max(28).default(1), centerLat: z.number().finite().min(-90).max(90).optional(), centerLng: z.number().finite().min(-180).max(180).optional(), radiusKm: z.number().finite().positive().max(500).optional(), playAsSoonAsSynced: z.boolean().default(false), layout: z.string().default("AD_NAV_OFFER"), offer: z.record(z.string(), z.string()).optional() });
const safe = (value: unknown) => JSON.parse(JSON.stringify(value, (_key, item) => typeof item === "bigint" ? Number(item) : item));
function errorResponse(error: unknown) { const status = error instanceof AdminAuthError ? error.status : 500; return NextResponse.json({ error: { message: status === 500 ? "Admin campaign service unavailable" : "Admin access required" } }, { status }); }
const campaignDate = (value: string | undefined, timezone: string, end = false) => { if (!value) return undefined; const suffix = timezone === "Asia/Kolkata" ? "+05:30" : "Z"; return new Date(`${value}T${end ? "23:59:59.999" : "00:00:00.000"}${suffix}`); };

export async function GET() {
  try { await getAuthenticatedAdmin(); const campaigns = await webPrisma.campaign.findMany({ orderBy: { updatedAt: "desc" }, include: { creatives: { where: { status: "ACTIVE" }, include: { asset: true }, orderBy: { displayOrder: "asc" }, take: 1 }, assignments: { where: { active: true }, select: { displayId: true } } } }); return NextResponse.json({ data: safe(campaigns.map(campaign => ({ ...campaign, selectedScreens: campaign.assignments.length, creative: campaign.creatives[0] ?? null }))) }); } catch (error) { return errorResponse(error); }
}

export async function POST(request: Request) {
  try { const admin = await getAuthenticatedAdmin(); const parsed = createSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: { message: "Provide a campaign name and valid schedule." } }, { status: 422 }); const input = parsed.data; const immediate = input.playAsSoonAsSynced; const metadata = { campaignType: "INTERNAL_TEST", playAsSoonAsSynced: immediate, adminSchedule: { startTime: input.startTime, endTime: input.endTime, days: input.days, timezone: input.timezone, frequency: input.frequency, playsPerLoop: input.playsPerLoop }, target: { mode: input.centerLat !== undefined && input.centerLng !== undefined ? "RADIUS" : "MANUAL_SCREENS", centerLat: input.centerLat, centerLng: input.centerLng, radiusKm: input.radiusKm }, advertiser: input.advertiser ?? "", frequency: input.frequency, playsPerLoop: input.playsPerLoop }; const campaign = await webPrisma.campaign.create({ data: { name: input.name, status: "DRAFT", startsAt: immediate ? new Date() : campaignDate(input.startDate, input.timezone), endsAt: campaignDate(input.endDate, input.timezone, true), timezone: input.timezone, layout: input.layout, campaignCenterLat: input.centerLat, campaignCenterLng: input.centerLng, radiusKm: input.radiusKm, commercialFundingStatus: "INTERNAL_TEST", metadata } }); await webPrisma.auditLog.create({ data: { actorRole: admin.role, action: "CAMPAIGN_CREATED", entityType: "Campaign", entityId: campaign.id, after: { name: campaign.name, status: campaign.status, campaignType: "INTERNAL_TEST" } } }); return NextResponse.json({ data: safe(campaign) }, { status: 201 }); } catch (error) { return errorResponse(error); }
}
